# Site
url: "https://www.melihkocaturk.com"
lang: tr
title: Melih Kocatürk
subtitle: Gayrimenkul Yatırım, Değerleme ve Pazarlama Danışmanlığı
description: Gayrimenkul danışmanından ipuçları ve stratejiler, emlak yatırımı, konut alım-satımı ve emlak sektörü hakkında güvenilir bilgiler...
words_per_minute: 190

# Contact
contact:
  gsm: +90 546 566 55 09
  phone: +90 212 397 11 00
  email: melih.kocaturk@kww.com.tr
  address: Keller Williams Fores, Halide Edip Adıvar Mh. Akar Cd. No:22/A Kat:3 Şişli/İstanbul

# Permalinks
permalink: /:title

# Pagination
paginate: 5
paginate_path: /sayfa:num/

# Google Analytics
google_analytics: G-D81YCKRVTX

# Google Adsense
google_adsense: 1369915303743120

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Include Directories
include: ['_tools', '_pages']